In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
raw_data = pd.read_csv('Absenteeism_data.csv')

In [3]:
raw_data

ID  Reason for Absence        Date  Transportation Expense  \
0    11                  26  07-07-2015                     289   
1    36                   0  14-07-2015                     118   
2     3                  23  15-07-2015                     179   
3     7                   7  16-07-2015                     279   
4    11                  23  23-07-2015                     289   
..   ..                 ...         ...                     ...   
695  17                  10  23-05-2018                     179   
696  28                   6  23-05-2018                     225   
697  18                  10  24-05-2018                     330   
698  25                  23  24-05-2018                     235   
699  15                  28  31-05-2018                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  
0            1         2     1                          4  
1            1         1     0                          0  
2            1         0     0                          2  
3            1         2     0                          4  
4            1         2     1                          2  
..         ...       ...   ...                        ...  
695          2         2     0                          8  
696          1         1     2                          3  
697          2         0     0                          8  
698          3         0     0                          2  
699          1         1     1                          2  

[700 rows x 12 columns]

In [4]:
fd=raw_data.copy()

In [5]:
fd.head(1)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07-07-2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4

In [6]:
fd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


In [7]:
fd['Date'].unique()

array(['07-07-2015', '14-07-2015', '15-07-2015', '16-07-2015',
       '23-07-2015', '10-07-2015', '17-07-2015', '24-07-2015',
       '06-07-2015', '13-07-2015', '20-07-2015', '27-07-2015',
       '30-07-2015', '05-08-2015', '12-08-2015', '03-08-2015',
       '10-08-2015', '14-08-2015', '17-08-2015', '24-08-2015',
       '04-08-2015', '19-08-2015', '28-08-2015', '27-08-2015',
       '20-08-2015', '21-08-2015', '01-09-2015', '07-09-2015',
       '08-09-2015', '09-09-2015', '13-09-2015', '14-09-2015',
       '24-09-2015', '04-09-2015', '21-09-2015', '28-09-2015',
       '15-09-2015', '22-09-2015', '29-09-2015', '16-09-2015',
       '23-09-2015', '30-09-2015', '11-09-2015', '18-09-2015',
       '25-09-2015', '06-10-2015', '13-10-2015', '14-10-2015',
       '15-10-2015', '16-10-2015', '21-10-2015', '22-10-2015',
       '20-10-2015', '23-10-2015', '30-10-2015', '05-11-2015',
       '04-11-2015', '12-11-2015', '19-11-2015', '02-11-2015',
       '09-11-2015', '16-11-2015', '18-11-2015', '20-11

In [8]:
type(fd['Date'])

pandas.core.series.Series

In [9]:
fd.isna().sum()

ID                           0
Reason for Absence           0
Date                         0
Transportation Expense       0
Distance to Work             0
Age                          0
Daily Work Load Average      0
Body Mass Index              0
Education                    0
Children                     0
Pets                         0
Absenteeism Time in Hours    0
dtype: int64

In [10]:
fd['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [11]:
fd['Transportation Expense'].unique()

array([289, 118, 179, 279, 361, 260, 155, 235, 246, 189, 248, 330, 157,
       291, 184, 225, 369, 388, 378, 228, 300, 268, 231, 233], dtype=int64)

In [12]:
fd.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07-07-2015                     289   
1  36                   0  14-07-2015                     118   
2   3                  23  15-07-2015                     179   
3   7                   7  16-07-2015                     279   
4  11                  23  23-07-2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [13]:
fd = fd.drop('ID',axis = True)

In [14]:
fd.head(1)

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07-07-2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4

In [15]:
pd.options.display.max_columns =None
pd.options.display.max_rows =None

In [16]:
fd['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [17]:
fd['Reason for Absence'].max()

28

In [18]:
fd['Reason for Absence'].min()

0

In [19]:
sorted(fd['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

In [20]:
fd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Reason for Absence         700 non-null    int64  
 1   Date                       700 non-null    object 
 2   Transportation Expense     700 non-null    int64  
 3   Distance to Work           700 non-null    int64  
 4   Age                        700 non-null    int64  
 5   Daily Work Load Average    700 non-null    float64
 6   Body Mass Index            700 non-null    int64  
 7   Education                  700 non-null    int64  
 8   Children                   700 non-null    int64  
 9   Pets                       700 non-null    int64  
 10  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(9), object(1)
memory usage: 60.3+ KB


In [21]:
sorted(fd['Reason for Absence'].astype(int))

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 4,
 4,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 15,
 16,
 16,
 16,

In [22]:
fd['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [23]:
reason_col = pd.get_dummies(fd['Reason for Absence'],drop_first=True)

In [24]:
reason_col.head(2)

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19  \
0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

   21  22  23  24  25  26  27  28  
0   0   0   0   0   0   1   0   0  
1   0   0   0   0   0   0   0   0

In [25]:
reason_col['checks']=reason_col.sum(axis=1)

In [26]:
reason_col.head()

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  21  22  \
0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   

   23  24  25  26  27  28  checks  
0   0   0   0   1   0   0       1  
1   0   0   0   0   0   0       0  
2   1   0   0   0   0   0       1  
3   0   0   0   0   0   0       1  
4   1   0   0   0   0   0       1

In [27]:
reason_col=reason_col.drop('checks',axis=True)

In [28]:
reason_col.head()

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  21  22  \
0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0   0   0   0   

   23  24  25  26  27  28  
0   0   0   0   1   0   0  
1   0   0   0   0   0   0  
2   1   0   0   0   0   0  
3   0   0   0   0   0   0  
4   1   0   0   0   0   0

In [29]:
fd.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [30]:
reason_col.columns.values

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       21, 22, 23, 24, 25, 26, 27, 28], dtype=object)

In [31]:
fd = fd.drop('Reason for Absence',axis = True)

In [32]:
fd.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07-07-2015                     289                36   33   
1  14-07-2015                     118                13   50   
2  15-07-2015                     179                51   38   
3  16-07-2015                     279                 5   39   
4  23-07-2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [33]:
reason_col.loc[:,1:14].max(axis=1)

0      0
1      0
2      0
3      1
4      0
5      0
6      0
7      0
8      0
9      0
10     1
11     1
12     1
13     1
14     0
15     1
16     0
17     0
18     1
19     0
20     1
21     1
22     1
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     1
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     1
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     1
76     0
77     0
78     0
79     0
80     0
81     0
82     1
83     0
84     0
85     1
86     0
87     1
88     0
89     1
90     0
91     0
92     1
93     0
94     0
95     0
96     1
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
1

In [34]:
reason_type_1 = reason_col.loc[:,1:14].max(axis=1)
reason_type_2 = reason_col.loc[:,15:17].max(axis=1)
reason_type_3 =  reason_col.loc[:,18:21].max(axis=1)
reason_type_4 = reason_col.loc[:,22:].max(axis=1)

In [35]:
fd = pd.concat([fd,reason_type_1,reason_type_2,reason_type_3,reason_type_4],axis = 1)
fd

Date  Transportation Expense  Distance to Work  Age  \
0    07-07-2015                     289                36   33   
1    14-07-2015                     118                13   50   
2    15-07-2015                     179                51   38   
3    16-07-2015                     279                 5   39   
4    23-07-2015                     289                36   33   
5    10-07-2015                     179                51   38   
6    17-07-2015                     361                52   28   
7    24-07-2015                     260                50   36   
8    06-07-2015                     155                12   34   
9    13-07-2015                     235                11   37   
10   20-07-2015                     260                50   36   
11   14-07-2015                     260                50   36   
12   15-07-2015                     260                50   36   
13   15-07-2015                     179                51   38   
14   15-07-2015                     179                51   38   
15   17-07-2015                     246                25   41   
16   17-07-2015                     179                51   38   
17   27-07-2015                     179                51   38   
18   30-07-2015                     189                29   33   
19   05-08-2015                     248                25   47   
20   12-08-2015                     330                16   28   
21   03-08-2015                     179                51   38   
22   10-08-2015                     361                52   28   
23   14-08-2015                     260                50   36   
24   17-08-2015                     289                36   33   
25   24-08-2015                     361                52   28   
26   04-08-2015                     289                36   33   
27   12-08-2015                     157                27   29   
28   19-08-2015                     289                36   33   
29   28-08-2015                     179                51   38   
30   17-08-2015                     179                51   38   
31   27-08-2015                     235                29   48   
32   27-08-2015                     235                11   37   
33   17-08-2015                     235                29   48   
34   17-08-2015                     179                51   38   
35   17-08-2015                     361                52   28   
36   04-08-2015                     289                36   33   
37   20-08-2015                     291                50   32   
38   21-08-2015                     235                29   48   
39   28-08-2015                     260                50   36   
40   01-09-2015                     184                42   27   
41   07-09-2015                     118                10   37   
42   01-09-2015                     179                51   38   
43   08-09-2015                     235                20   43   
44   09-09-2015                     155                12   34   
45   13-09-2015                     118                10   37   
46   14-09-2015                     179                51   38   
47   24-09-2015                     291                31   40   
48   04-09-2015                     260                50   36   
49   14-09-2015                     291                31   40   
50   21-09-2015                     260                50   36   
51   28-09-2015                     225                26   28   
52   08-09-2015                     225                26   28   
53   15-09-2015                     118                10   37   
54   22-09-2015                     289                36   33   
55   29-09-2015                     118                13   50   
56   16-09-2015                     225                26   28   
57   23-09-2015                     179                51   38   
58   30-09-2015                     369                17   31   
59   11-09-2015                     248            

In [36]:
fd.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [37]:
columns_name = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'reason_1','reason_2','reason_3','reason_4']

In [38]:
fd.columns = columns_name

In [39]:
fd.head(1)

Date  Transportation Expense  Distance to Work  Age  \
0  07-07-2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   

   Absenteeism Time in Hours  reason_1  reason_2  reason_3  reason_4  
0                          4         0         0         0         1

In [40]:
column_names_reorder = ['reason_1',
       'reason_2', 'reason_3', 'reason_4','Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [41]:
fd=fd[column_names_reorder]

In [42]:
fd.head(1)

reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  07-07-2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4

In [43]:
df_reason_mod = fd.copy()

In [44]:
type(df_reason_mod['Date'][0])

str

In [45]:
df_reason_mod['Date']=pd.to_datetime(df_reason_mod['Date'])

C:\Users\amit7\AppData\Local\Temp\ipykernel_8880\982597742.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df_reason_mod['Date']=pd.to_datetime(df_reason_mod['Date'])


In [46]:
df_reason_mod['Date'].head()

0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
Name: Date, dtype: datetime64[ns]

In [47]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'] , format=('%d/%m/%Y'))

In [48]:
type(df_reason_mod['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [49]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   reason_1                   700 non-null    uint8         
 1   reason_2                   700 non-null    uint8         
 2   reason_3                   700 non-null    uint8         
 3   reason_4                   700 non-null    uint8         
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64         
 6   Distance to Work           700 non-null    int64         
 7   Age                        700 non-null    int64         
 8   Daily Work Load Average    700 non-null    float64       
 9   Body Mass Index            700 non-null    int64         
 10  Education                  700 non-null    int64         
 11  Children                   700 non-null    int64         
 12  Pets    

In [50]:
df_reason_mod['Date'][0].month

7

In [51]:
df_reason_mod['Date'][0].year

2015

In [52]:
df_reason_mod['Date'][0].day

7

In [53]:
list_month =[]

In [54]:
for i in range(700):
    list_month.append(df_reason_mod['Date'][i].month)

In [55]:
df_reason_mod['month value'] = list_month

In [56]:
df_reason_mod.head()

reason_1  reason_2  reason_3  reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  month value  
0         2     1                          4            7  
1         1     0                          0            7  
2         0     0                          2            7  
3         2     0                          4            7  
4         2     1                          2            7

In [57]:
def date_to_weekdays(date_value):
    return date_value.weekday()

In [58]:
df_reason_mod['Day of the week'] = df_reason_mod['Date'].apply(date_to_weekdays)

In [59]:
df_reason_mod.head()

reason_1  reason_2  reason_3  reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  month value  Day of the week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

In [60]:
df_reason_mod=df_reason_mod.drop('Date',axis=True)

In [61]:
df_reason_mod.head(0)

Empty DataFrame
Columns: [reason_1, reason_2, reason_3, reason_4, Transportation Expense, Distance to Work, Age, Daily Work Load Average, Body Mass Index, Education, Children, Pets, Absenteeism Time in Hours, month value, Day of the week]
Index: []

In [62]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   reason_1                   700 non-null    uint8  
 1   reason_2                   700 non-null    uint8  
 2   reason_3                   700 non-null    uint8  
 3   reason_4                   700 non-null    uint8  
 4   Transportation Expense     700 non-null    int64  
 5   Distance to Work           700 non-null    int64  
 6   Age                        700 non-null    int64  
 7   Daily Work Load Average    700 non-null    float64
 8   Body Mass Index            700 non-null    int64  
 9   Education                  700 non-null    int64  
 10  Children                   700 non-null    int64  
 11  Pets                       700 non-null    int64  
 12  Absenteeism Time in Hours  700 non-null    int64  
 13  month value                700 non-null    int64  

In [63]:
type(df_reason_mod['reason_1'][0])

numpy.uint8

In [64]:
df_reason_mod['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [65]:
df_reason_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [66]:
new_df = df_reason_mod.copy()

In [67]:
new_df['Education'] = new_df['Education'].map({1:0,2:1,3:1,4:1})

In [68]:
new_df.head(3)

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   

   Children  Pets  Absenteeism Time in Hours  month value  Day of the week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2

In [69]:
new_df['Education'].unique()

array([0, 1], dtype=int64)

In [70]:
new_df['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

In [71]:
new_df.shape

(700, 15)

In [72]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   reason_1                   700 non-null    uint8  
 1   reason_2                   700 non-null    uint8  
 2   reason_3                   700 non-null    uint8  
 3   reason_4                   700 non-null    uint8  
 4   Transportation Expense     700 non-null    int64  
 5   Distance to Work           700 non-null    int64  
 6   Age                        700 non-null    int64  
 7   Daily Work Load Average    700 non-null    float64
 8   Body Mass Index            700 non-null    int64  
 9   Education                  700 non-null    int64  
 10  Children                   700 non-null    int64  
 11  Pets                       700 non-null    int64  
 12  Absenteeism Time in Hours  700 non-null    int64  
 13  month value                700 non-null    int64  

# Final checkpoint

In [73]:
df_preprocess = new_df.copy()

In [74]:
df_preprocess.head(10)

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   
5         0         0         0         1                     179   
6         0         0         0         1                     361   
7         0         0         0         1                     260   
8         0         0         1         0                     155   
9         0         0         0         1                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   
5                51   38                  239.554               31          0   
6                52   28                  239.554               27          0   
7                50   36                  239.554               23          0   
8                12   34                  239.554               25          0   
9                11   37                  239.554               29          1   

   Children  Pets  Absenteeism Time in Hours  month value  Day of the week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3  
5         0     0                          2           10                2  
6         1     4                          8            7                4  
7         4     0                          4            7                4  
8         2     0                         40            6                6  
9         1     1                          8            7                0

# Save the data in csv file

In [75]:
df_preprocess.to_csv('Absenteeism_preprocesed.csv',index=False)

# Creating Logistic regression to predict Absenteeism 

In [76]:
data_preprocessed = pd.read_csv('Absenteeism_preprocesed.csv')

In [77]:
data_preprocessed.head(2)

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   

   Children  Pets  Absenteeism Time in Hours  month value  Day of the week  
0         2     1                          4            7                1  
1         1     0                          0            7                1

In [78]:
data_preprocessed.describe()

reason_1    reason_2    reason_3    reason_4  Transportation Expense  \
count  700.000000  700.000000  700.000000  700.000000              700.000000   
mean     0.250000    0.008571    0.090000    0.597143              222.347143   
std      0.433322    0.092250    0.286386    0.490823               66.312960   
min      0.000000    0.000000    0.000000    0.000000              118.000000   
25%      0.000000    0.000000    0.000000    0.000000              179.000000   
50%      0.000000    0.000000    0.000000    1.000000              225.000000   
75%      0.250000    0.000000    0.000000    1.000000              260.000000   
max      1.000000    1.000000    1.000000    1.000000              388.000000   

       Distance to Work         Age  Daily Work Load Average  Body Mass Index  \
count        700.000000  700.000000               700.000000       700.000000   
mean          29.892857   36.417143               271.801774        26.737143   
std           14.804446    6.379083                40.021804         4.254701   
min            5.000000   27.000000               205.917000        19.000000   
25%           16.000000   31.000000               241.476000        24.000000   
50%           26.000000   37.000000               264.249000        25.000000   
75%           50.000000   40.000000               294.217000        31.000000   
max           52.000000   58.000000               378.884000        38.000000   

        Education    Children        Pets  Absenteeism Time in Hours  \
count  700.000000  700.000000  700.000000                 700.000000   
mean     0.167143    1.021429    0.687143                   6.761429   
std      0.373370    1.112215    1.166095                  12.670082   
min      0.000000    0.000000    0.000000                   0.000000   
25%      0.000000    0.000000    0.000000                   2.000000   
50%      0.000000    1.000000    0.000000                   3.000000   
75%      0.000000    2.000000    1.000000                   8.000000   
max      1.000000    4.000000    8.000000                 120.000000   

       month value  Day of the week  
count   700.000000       700.000000  
mean      6.897143         2.410000  
std       3.342319         1.761669  
min       1.000000         0.000000  
25%       4.000000         1.000000  
50%       7.000000         2.000000  
75%      10.000000         4.000000  
max      12.000000         6.000000

In [79]:
data_preprocessed['Absenteeism Time in Hours'].unique()

array([  4,   0,   2,   8,  40,   1,   7,   3,  32,   5,  16,  24,  64,
        56,  80, 120, 112, 104,  48], dtype=int64)

In [80]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [81]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>3,1,0)

In [82]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [83]:
data_preprocessed['Excessive Absenteeism'] = targets

In [84]:
data_preprocessed.head()

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  month value  Day of the week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [85]:
data_with_targets = data_preprocessed.drop('Absenteeism Time in Hours',axis=True)

In [86]:
data_with_targets.head(0)

Empty DataFrame
Columns: [reason_1, reason_2, reason_3, reason_4, Transportation Expense, Distance to Work, Age, Daily Work Load Average, Body Mass Index, Education, Children, Pets, month value, Day of the week, Excessive Absenteeism]
Index: []

In [87]:
data_with_targets.shape

(700, 15)

In [88]:
x = data_with_targets.iloc[:,:14]

In [89]:
x.head(0)

Empty DataFrame
Columns: [reason_1, reason_2, reason_3, reason_4, Transportation Expense, Distance to Work, Age, Daily Work Load Average, Body Mass Index, Education, Children, Pets, month value, Day of the week]
Index: []

In [90]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [91]:
from sklearn.preprocessing import StandardScaler

In [92]:
absenteeism_scaler = StandardScaler()


In [93]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [94]:
x.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'month value', 'Day of the week'], dtype=object)

In [95]:
# use list comprehension to iterate over the list
columns_to_scale = ['Transportation Expense', 'Distance to Work', 'Age','Daily Work Load Average', 'Body Mass Index', 'Children','Pets', 'month value', 'Day of the week']

In [96]:
# declare a scaler object, specifying the columns you want to scale
absenteeism_scaler = CustomScaler(columns_to_scale)

In [97]:
absenteeism_scaler.fit(x)

C:\Users\amit7\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

In [98]:
x_scaler=absenteeism_scaler.transform(x)

In [99]:
x_scaler

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0           0         0         0         1                1.005844   
1           0         0         0         0               -1.574681   
2           0         0         0         1               -0.654143   
3           1         0         0         0                0.854936   
4           0         0         0         1                1.005844   
5           0         0         0         1               -0.654143   
6           0         0         0         1                2.092381   
7           0         0         0         1                0.568211   
8           0         0         1         0               -1.016322   
9           0         0         0         1                0.190942   
10          1         0         0         0                0.568211   
11          1         0         0         0                0.568211   
12          1         0         0         0                0.568211   
13          1         0         0         0               -0.654143   
14          0         0         0         1               -0.654143   
15          1         0         0         0                0.356940   
16          0         0         0         1               -0.654143   
17          0         0         1         0               -0.654143   
18          1         0         0         0               -0.503235   
19          0         0         0         1                0.387122   
20          1         0         0         0                1.624567   
21          1         0         0         0               -0.654143   
22          1         0         0         0                2.092381   
23          0         0         0         1                0.568211   
24          0         0         1         0                1.005844   
25          0         0         0         1                2.092381   
26          0         0         0         1                1.005844   
27          0         0         0         1               -0.986140   
28          0         0         1         0                1.005844   
29          0         0         0         1               -0.654143   
30          0         0         1         0               -0.654143   
31          0         0         1         0                0.190942   
32          0         0         0         1                0.190942   
33          0         0         1         0                0.190942   
34          0         0         0         1               -0.654143   
35          0         0         0         1                2.092381   
36          0         0         0         1                1.005844   
37          1         0         0         0                1.036026   
38          0         0         0         1                0.190942   
39          0         0         0         1                0.568211   
40          0         0         0         1               -0.578689   
41          0         0         0         1               -1.574681   
42          0         0         0         1               -0.654143   
43          0         0         1         0                0.190942   
44          0         0         0         1               -1.016322   
45          0         0         0         1               -1.574681   
46          0         0         0         1               -0.654143   
47          0         0         0         1                1.036026   
48          0         0         0         1                0.568211   
49          1         0         0         0                1.036026   
50          0         0         0         0                0.568211   
51          0         0         0         0                0.040034   
52          0         0         0         1                0.040034   
53          0         0         0         1               -1.574681   
54          0         0         0         0                1.005844   
55          0         0      

In [100]:
x_scaler.shape

(700, 14)

In [101]:
from sklearn.model_selection import train_test_split

In [102]:
train_test_split(x_scaler,targets)

[     reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
 389         0         0         0         1               -0.654143   
 437         0         0         0         1               -0.654143   
 363         0         0         0         1                1.005844   
 549         0         0         0         0                1.005844   
 393         0         0         0         1                0.568211   
 352         1         0         0         0                0.190942   
 471         1         0         0         0                0.040034   
 239         0         0         0         1               -1.574681   
 162         1         0         0         0                0.387122   
 495         0         0         0         1                0.356940   
 183         0         0         0         1                0.040034   
 379         0         0         0         1               -0.654143   
 373         0         0         0         1                0.56

In [103]:
x_train,x_test,y_train,y_test =train_test_split(x_scaler,targets,train_size = 0.8,random_state=20)

In [104]:
x_train.shape

(560, 14)

In [105]:
y_train.shape[0]

560

In [106]:
x_test.shape

(140, 14)

In [107]:
y_test.shape

(140,)

# Logistic regression with sklearn

In [108]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [109]:
reg = LogisticRegression()

In [110]:
reg.fit(x_train,y_train)

LogisticRegression()

In [111]:
reg.score(x_train,y_train)

0.7660714285714286

In [112]:
reg.intercept_

array([-1.60991897])

In [113]:
reg.coef_

array([[ 2.78809595,  0.92273475,  3.10358519,  0.81724476,  0.62737945,
        -0.02990801, -0.17344994, -0.02273184,  0.2816181 , -0.27058935,
         0.36063506, -0.27446609,  0.01379249, -0.07594179]])

In [114]:
x.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'month value', 'Day of the week'], dtype=object)

In [115]:
feature_name = x.columns.values

In [116]:
summary_table = pd.DataFrame(columns=['feature_name'] , data = feature_name)

In [117]:
summary_table['coefficient'] = np.transpose(reg.coef_)

In [118]:
summary_table

feature_name  coefficient
0                  reason_1     2.788096
1                  reason_2     0.922735
2                  reason_3     3.103585
3                  reason_4     0.817245
4    Transportation Expense     0.627379
5          Distance to Work    -0.029908
6                       Age    -0.173450
7   Daily Work Load Average    -0.022732
8           Body Mass Index     0.281618
9                 Education    -0.270589
10                 Children     0.360635
11                     Pets    -0.274466
12              month value     0.013792
13          Day of the week    -0.075942

In [119]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

feature_name  coefficient
0                 Intercept    -1.609919
1                  reason_1     2.788096
2                  reason_2     0.922735
3                  reason_3     3.103585
4                  reason_4     0.817245
5    Transportation Expense     0.627379
6          Distance to Work    -0.029908
7                       Age    -0.173450
8   Daily Work Load Average    -0.022732
9           Body Mass Index     0.281618
10                Education    -0.270589
11                 Children     0.360635
12                     Pets    -0.274466
13              month value     0.013792
14          Day of the week    -0.075942

In [120]:
summary_table['odds ratio'] = np.exp(summary_table.coefficient)

In [121]:
summary_table

feature_name  coefficient  odds ratio
0                 Intercept    -1.609919    0.199904
1                  reason_1     2.788096   16.250049
2                  reason_2     0.922735    2.516162
3                  reason_3     3.103585   22.277678
4                  reason_4     0.817245    2.264253
5    Transportation Expense     0.627379    1.872697
6          Distance to Work    -0.029908    0.970535
7                       Age    -0.173450    0.840759
8   Daily Work Load Average    -0.022732    0.977525
9           Body Mass Index     0.281618    1.325273
10                Education    -0.270589    0.762930
11                 Children     0.360635    1.434240
12                     Pets    -0.274466    0.759978
13              month value     0.013792    1.013888
14          Day of the week    -0.075942    0.926870

In [122]:
summary_table = summary_table.sort_index()

In [123]:
summary_table.sort_values('odds ratio',ascending=False)

feature_name  coefficient  odds ratio
3                  reason_3     3.103585   22.277678
1                  reason_1     2.788096   16.250049
2                  reason_2     0.922735    2.516162
4                  reason_4     0.817245    2.264253
5    Transportation Expense     0.627379    1.872697
11                 Children     0.360635    1.434240
9           Body Mass Index     0.281618    1.325273
13              month value     0.013792    1.013888
8   Daily Work Load Average    -0.022732    0.977525
6          Distance to Work    -0.029908    0.970535
14          Day of the week    -0.075942    0.926870
7                       Age    -0.173450    0.840759
10                Education    -0.270589    0.762930
12                     Pets    -0.274466    0.759978
0                 Intercept    -1.609919    0.199904

In [124]:
reg.score(x_test,y_test)

0.7571428571428571

In [125]:
import pickle

In [126]:
with open ('model','wb') as file:
    pickle.dump(reg,file)

In [127]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)

In [130]:
from absenteeism_module import *